log_file=log/YYYYMMDD.txt
station_info=resource/sta.m3
mask_nc=resource/mask010.nc
default_plugin=resource/plugin/ecmwf.json

# 回算起报时间列表，逗号分隔；空表示实时
rpt_list=2025100100,2025100112
# rpt_list=2025010100

ipt_model=0
ipt_obs=1
ipt_type=m4
opt_type=m4
over_w=0

start_dtime=36
end_dtime=252
inter_dtime1=12
inter_dtime2=12
report_inter=12

res=0.1
clip_coords=70.0,140.0,0.0,60.0
pool_num=8
